# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import colistracker_pb2 as colistracker__pb2


class TrackingStub(object):
    """The tracking service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPacketStatus = channel.unary_unary(
                '/colistracker.Tracking/GetPacketStatus',
                request_serializer=colistracker__pb2.TrackingRequest.SerializeToString,
                response_deserializer=colistracker__pb2.TrackingResponse.FromString,
                )


class TrackingServicer(object):
    """The tracking service definition.
    """

    def GetPacketStatus(self, request, context):
        """Get packet tracking status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPacketStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPacketStatus,
                    request_deserializer=colistracker__pb2.TrackingRequest.FromString,
                    response_serializer=colistracker__pb2.TrackingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'colistracker.Tracking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tracking(object):
    """The tracking service definition.
    """

    @staticmethod
    def GetPacketStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colistracker.Tracking/GetPacketStatus',
            colistracker__pb2.TrackingRequest.SerializeToString,
            colistracker__pb2.TrackingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
