# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: colistracker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='colistracker.proto',
  package='colistracker',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63olistracker.proto\x12\x0c\x63olistracker\")\n\x0fTrackingRequest\x12\x16\n\x0etrackingNumber\x18\x01 \x01(\t\"O\n\x0fPackageActivity\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\x05\x12\x0c\n\x04time\x18\x04 \x01(\x05\"V\n\x10TrackingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x31\n\nactivities\x18\x02 \x03(\x0b\x32\x1d.colistracker.PackageActivity2^\n\x08Tracking\x12R\n\x0fGetPacketStatus\x12\x1d.colistracker.TrackingRequest\x1a\x1e.colistracker.TrackingResponse\"\x00\x62\x06proto3'
)




_TRACKINGREQUEST = _descriptor.Descriptor(
  name='TrackingRequest',
  full_name='colistracker.TrackingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trackingNumber', full_name='colistracker.TrackingRequest.trackingNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=77,
)


_PACKAGEACTIVITY = _descriptor.Descriptor(
  name='PackageActivity',
  full_name='colistracker.PackageActivity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='colistracker.PackageActivity.location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='colistracker.PackageActivity.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='colistracker.PackageActivity.date', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='colistracker.PackageActivity.time', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=158,
)


_TRACKINGRESPONSE = _descriptor.Descriptor(
  name='TrackingResponse',
  full_name='colistracker.TrackingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='colistracker.TrackingResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='activities', full_name='colistracker.TrackingResponse.activities', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=246,
)

_TRACKINGRESPONSE.fields_by_name['activities'].message_type = _PACKAGEACTIVITY
DESCRIPTOR.message_types_by_name['TrackingRequest'] = _TRACKINGREQUEST
DESCRIPTOR.message_types_by_name['PackageActivity'] = _PACKAGEACTIVITY
DESCRIPTOR.message_types_by_name['TrackingResponse'] = _TRACKINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrackingRequest = _reflection.GeneratedProtocolMessageType('TrackingRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRACKINGREQUEST,
  '__module__' : 'colistracker_pb2'
  # @@protoc_insertion_point(class_scope:colistracker.TrackingRequest)
  })
_sym_db.RegisterMessage(TrackingRequest)

PackageActivity = _reflection.GeneratedProtocolMessageType('PackageActivity', (_message.Message,), {
  'DESCRIPTOR' : _PACKAGEACTIVITY,
  '__module__' : 'colistracker_pb2'
  # @@protoc_insertion_point(class_scope:colistracker.PackageActivity)
  })
_sym_db.RegisterMessage(PackageActivity)

TrackingResponse = _reflection.GeneratedProtocolMessageType('TrackingResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRACKINGRESPONSE,
  '__module__' : 'colistracker_pb2'
  # @@protoc_insertion_point(class_scope:colistracker.TrackingResponse)
  })
_sym_db.RegisterMessage(TrackingResponse)



_TRACKING = _descriptor.ServiceDescriptor(
  name='Tracking',
  full_name='colistracker.Tracking',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=248,
  serialized_end=342,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPacketStatus',
    full_name='colistracker.Tracking.GetPacketStatus',
    index=0,
    containing_service=None,
    input_type=_TRACKINGREQUEST,
    output_type=_TRACKINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRACKING)

DESCRIPTOR.services_by_name['Tracking'] = _TRACKING

# @@protoc_insertion_point(module_scope)
