// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avros.UpdateCommand
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Parcel : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Parcel\",\"namespace\":\"Avros.UpdateCommand\",\"fields\":[{\"na" +
				"me\":\"TrackingNumber\",\"type\":\"string\"},{\"name\":\"Carrier\",\"type\":{\"type\":\"enum\",\"n" +
				"ame\":\"Carrier\",\"namespace\":\"Avros.UpdateCommand\",\"symbols\":[\"DHL\",\"LA_POSTE\",\"UP" +
				"S\"]}}]}");
		private string _TrackingNumber;
		private Avros.UpdateCommand.Carrier _Carrier;
		public virtual Schema Schema
		{
			get
			{
				return Parcel._SCHEMA;
			}
		}
		public string TrackingNumber
		{
			get
			{
				return this._TrackingNumber;
			}
			set
			{
				this._TrackingNumber = value;
			}
		}
		public Avros.UpdateCommand.Carrier Carrier
		{
			get
			{
				return this._Carrier;
			}
			set
			{
				this._Carrier = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.TrackingNumber;
			case 1: return this.Carrier;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.TrackingNumber = (System.String)fieldValue; break;
			case 1: this.Carrier = (Avros.UpdateCommand.Carrier)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
