// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avros.UpdateCommand
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Wrapper : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Wrapper"",""namespace"":""Avros.UpdateCommand"",""fields"":[{""name"":""Parcel"",""type"":{""type"":""record"",""name"":""Parcel"",""namespace"":""Avros.UpdateCommand"",""fields"":[{""name"":""TrackingNumber"",""type"":""string""},{""name"":""Carrier"",""type"":{""type"":""enum"",""name"":""Carrier"",""namespace"":""Avros.UpdateCommand"",""symbols"":[""DHL"",""LA_POSTE"",""UPS""]}}]}}]}");
		private Avros.UpdateCommand.Parcel _Parcel;
		public virtual Schema Schema
		{
			get
			{
				return Wrapper._SCHEMA;
			}
		}
		public Avros.UpdateCommand.Parcel Parcel
		{
			get
			{
				return this._Parcel;
			}
			set
			{
				this._Parcel = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Parcel;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Parcel = (Avros.UpdateCommand.Parcel)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
