[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

__Colis Tracker__ is an application for tracking packages from multiple providers. It allows the user to add new packages to track and see their status and history.

In addition, __Colis Tracker__ is used to study and evaluate technology, patterns and frameworks. The functional requirements are simple enough to leave room for concentration on quality goals.

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

The main purpose of __Colis Tracker__ is to track parcels and present their status and history in a useful way to the user.

Main features :

- Add new packages to track
- Visualize parcels current statuses in near real-time
- Visualize parcels history
- Visualize archived parcels
- Support as many tracking provider as possible

The application is to be used by only one user.

Tracking info should be retrieved using the providers APIs when available, or parse the providers tracking webpages.

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

[options="header",cols="1,2"]
|===
|Quality|Motivation
| Understandability| The functional requirements are simple enough to allow a simple, understandable solution that allows focus on learning.
| Documentability | All choices should be documented to allow easy transfer of knowledge between members of the technical team.
| Testability | The architecture should allow easy testingof all main building blocks

|===



=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****


The following list contains the most important personas for this application :

[options="header",cols="1,2"]
|===
|Role/Name|Expectations
| DevOps Team | Learn about new ways to build, deploy and host modern applications
| Developers  | Learn about new ways to develop modern applications.
| Application Users | Looking for an open-source parcel tracking application which is self-hostable, and support as many providers as possible.
| Germain Lefevbre  | --
|===


