
// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avros.HistoryEvent
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Details : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Details"",""namespace"":""Avros.HistoryEvent"",""fields"":[{""name"":""Pieces"",""type"":[""null"",""int""]},{""name"":""Weight"",""type"":[""null"",{""type"":""record"",""name"":""UnitValue"",""namespace"":""Avros.HistoryEvent"",""fields"":[{""name"":""Value"",""type"":""float""},{""name"":""Unit"",""type"":""string""}]}]},{""name"":""Width"",""type"":[""null"",""UnitValue""]},{""name"":""Height"",""type"":[""null"",""UnitValue""]},{""name"":""Length"",""type"":[""null"",""UnitValue""]}]}");
		private System.Nullable<int> _Pieces;
		private Avros.HistoryEvent.UnitValue _Weight;
		private Avros.HistoryEvent.UnitValue _Width;
		private Avros.HistoryEvent.UnitValue _Height;
		private Avros.HistoryEvent.UnitValue _Length;
		public virtual Schema Schema
		{
			get
			{
				return Details._SCHEMA;
			}
		}
		public System.Nullable<int> Pieces
		{
			get
			{
				return this._Pieces;
			}
			set
			{
				this._Pieces = value;
			}
		}
		public Avros.HistoryEvent.UnitValue Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				this._Weight = value;
			}
		}
		public Avros.HistoryEvent.UnitValue Width
		{
			get
			{
				return this._Width;
			}
			set
			{
				this._Width = value;
			}
		}
		public Avros.HistoryEvent.UnitValue Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				this._Height = value;
			}
		}
		public Avros.HistoryEvent.UnitValue Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				this._Length = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Pieces;
			case 1: return this.Weight;
			case 2: return this.Width;
			case 3: return this.Height;
			case 4: return this.Length;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Pieces = (System.Nullable<int>)fieldValue; break;
			case 1: this.Weight = (Avros.HistoryEvent.UnitValue)fieldValue; break;
			case 2: this.Width = (Avros.HistoryEvent.UnitValue)fieldValue; break;
			case 3: this.Height = (Avros.HistoryEvent.UnitValue)fieldValue; break;
			case 4: this.Length = (Avros.HistoryEvent.UnitValue)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
