// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avros.HistoryEvent
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Wrapper : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Wrapper"",""namespace"":""Avros.HistoryEvent"",""fields"":[{""name"":""Parcel"",""type"":{""type"":""record"",""name"":""Parcel"",""namespace"":""Avros.HistoryEvent"",""fields"":[{""name"":""TrackingNumber"",""type"":""string""},{""name"":""Carrier"",""type"":{""type"":""enum"",""name"":""Carrier"",""namespace"":""Avros.HistoryEvent"",""symbols"":[""DHL"",""LA_POSTE"",""UPS""]}}]}},{""name"":""Origin"",""type"":{""type"":""record"",""name"":""Address"",""namespace"":""Avros.HistoryEvent"",""fields"":[{""name"":""CountryCode"",""type"":[""null"",""string""]},{""name"":""City"",""type"":[""null"",""string""]},{""name"":""ZipCode"",""type"":[""null"",""string""]},{""name"":""Localisation"",""type"":[""null"",""string""]}]}},{""name"":""Destination"",""type"":""Address""},{""name"":""Details"",""type"":{""type"":""record"",""name"":""Details"",""namespace"":""Avros.HistoryEvent"",""fields"":[{""name"":""Pieces"",""type"":[""null"",""int""]},{""name"":""Weight"",""type"":[""null"",{""type"":""record"",""name"":""UnitValue"",""namespace"":""Avros.HistoryEvent"",""fields"":[{""name"":""Value"",""type"":""float""},{""name"":""Unit"",""type"":""string""}]}]},{""name"":""Width"",""type"":[""null"",""UnitValue""]},{""name"":""Height"",""type"":[""null"",""UnitValue""]},{""name"":""Length"",""type"":[""null"",""UnitValue""]}]}},{""name"":""Events"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""Event"",""namespace"":""Avros.HistoryEvent"",""fields"":[{""name"":""Status"",""type"":""string""},{""name"":""Description"",""type"":""string""},{""name"":""Timestamp"",""type"":""long"",""logicalType"":""timestamp-millis""}]}}}]}");
		private Avros.HistoryEvent.Parcel _Parcel;
		private Avros.HistoryEvent.Address _Origin;
		private Avros.HistoryEvent.Address _Destination;
		private Avros.HistoryEvent.Details _Details;
		private IList<Avros.HistoryEvent.Event> _Events;
		public virtual Schema Schema
		{
			get
			{
				return Wrapper._SCHEMA;
			}
		}
		public Avros.HistoryEvent.Parcel Parcel
		{
			get
			{
				return this._Parcel;
			}
			set
			{
				this._Parcel = value;
			}
		}
		public Avros.HistoryEvent.Address Origin
		{
			get
			{
				return this._Origin;
			}
			set
			{
				this._Origin = value;
			}
		}
		public Avros.HistoryEvent.Address Destination
		{
			get
			{
				return this._Destination;
			}
			set
			{
				this._Destination = value;
			}
		}
		public Avros.HistoryEvent.Details Details
		{
			get
			{
				return this._Details;
			}
			set
			{
				this._Details = value;
			}
		}
		public IList<Avros.HistoryEvent.Event> Events
		{
			get
			{
				return this._Events;
			}
			set
			{
				this._Events = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Parcel;
			case 1: return this.Origin;
			case 2: return this.Destination;
			case 3: return this.Details;
			case 4: return this.Events;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Parcel = (Avros.HistoryEvent.Parcel)fieldValue; break;
			case 1: this.Origin = (Avros.HistoryEvent.Address)fieldValue; break;
			case 2: this.Destination = (Avros.HistoryEvent.Address)fieldValue; break;
			case 3: this.Details = (Avros.HistoryEvent.Details)fieldValue; break;
			case 4: this.Events = (IList<Avros.HistoryEvent.Event>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
