// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.ineat.colistracker.historyevent
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Address : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Address"",""namespace"":""com.ineat.colistracker.historyevent"",""fields"":[{""name"":""CountryCode"",""doc"":""Code de pays, ex : DE"",""type"":[""null"",""string""]},{""name"":""City"",""doc"":""Ville, ex : Munich"",""type"":[""null"",""string""]},{""name"":""ZipCode"",""doc"":""Code postal, ex : 59115"",""type"":[""null"",""string""]},{""name"":""Localisation"",""doc"":""Rue / numéro / étage, ex : 30 rue du poivre"",""type"":[""null"",""string""]}]}");
		/// <summary>
		/// Code de pays, ex : DE
		/// </summary>
		private string _CountryCode;
		/// <summary>
		/// Ville, ex : Munich
		/// </summary>
		private string _City;
		/// <summary>
		/// Code postal, ex : 59115
		/// </summary>
		private string _ZipCode;
		/// <summary>
		/// Rue / numéro / étage, ex : 30 rue du poivre
		/// </summary>
		private string _Localisation;
		public virtual Schema Schema
		{
			get
			{
				return Address._SCHEMA;
			}
		}
		/// <summary>
		/// Code de pays, ex : DE
		/// </summary>
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				this._CountryCode = value;
			}
		}
		/// <summary>
		/// Ville, ex : Munich
		/// </summary>
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				this._City = value;
			}
		}
		/// <summary>
		/// Code postal, ex : 59115
		/// </summary>
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				this._ZipCode = value;
			}
		}
		/// <summary>
		/// Rue / numéro / étage, ex : 30 rue du poivre
		/// </summary>
		public string Localisation
		{
			get
			{
				return this._Localisation;
			}
			set
			{
				this._Localisation = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CountryCode;
			case 1: return this.City;
			case 2: return this.ZipCode;
			case 3: return this.Localisation;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CountryCode = (System.String)fieldValue; break;
			case 1: this.City = (System.String)fieldValue; break;
			case 2: this.ZipCode = (System.String)fieldValue; break;
			case 3: this.Localisation = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
