// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.ineat.colistracker.historyevent
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Details : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Details"",""namespace"":""com.ineat.colistracker.historyevent"",""fields"":[{""name"":""Pieces"",""doc"":""Nombre de colis"",""type"":[""null"",""int""]},{""name"":""Weight"",""doc"":""Poids, ex : 1.5kg"",""type"":[""null"",{""type"":""record"",""name"":""UnitValue"",""namespace"":""com.ineat.colistracker.historyevent"",""fields"":[{""name"":""Value"",""doc"":""Valeur, ex : 1.5"",""type"":""float""},{""name"":""Unit"",""doc"":""Unité, ex : kg"",""type"":""string""}]}]},{""name"":""Width"",""doc"":""Largeur, ex : 50cm"",""type"":[""null"",""UnitValue""]},{""name"":""Height"",""doc"":""Hauteur, ex : 1.5m"",""type"":[""null"",""UnitValue""]},{""name"":""Length"",""doc"":""Profondeur, ex : 300mm"",""type"":[""null"",""UnitValue""]}]}");
		/// <summary>
		/// Nombre de colis
		/// </summary>
		private System.Nullable<int> _Pieces;
		/// <summary>
		/// Poids, ex : 1.5kg
		/// </summary>
		private com.ineat.colistracker.historyevent.UnitValue _Weight;
		/// <summary>
		/// Largeur, ex : 50cm
		/// </summary>
		private com.ineat.colistracker.historyevent.UnitValue _Width;
		/// <summary>
		/// Hauteur, ex : 1.5m
		/// </summary>
		private com.ineat.colistracker.historyevent.UnitValue _Height;
		/// <summary>
		/// Profondeur, ex : 300mm
		/// </summary>
		private com.ineat.colistracker.historyevent.UnitValue _Length;
		public virtual Schema Schema
		{
			get
			{
				return Details._SCHEMA;
			}
		}
		/// <summary>
		/// Nombre de colis
		/// </summary>
		public System.Nullable<int> Pieces
		{
			get
			{
				return this._Pieces;
			}
			set
			{
				this._Pieces = value;
			}
		}
		/// <summary>
		/// Poids, ex : 1.5kg
		/// </summary>
		public com.ineat.colistracker.historyevent.UnitValue Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				this._Weight = value;
			}
		}
		/// <summary>
		/// Largeur, ex : 50cm
		/// </summary>
		public com.ineat.colistracker.historyevent.UnitValue Width
		{
			get
			{
				return this._Width;
			}
			set
			{
				this._Width = value;
			}
		}
		/// <summary>
		/// Hauteur, ex : 1.5m
		/// </summary>
		public com.ineat.colistracker.historyevent.UnitValue Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				this._Height = value;
			}
		}
		/// <summary>
		/// Profondeur, ex : 300mm
		/// </summary>
		public com.ineat.colistracker.historyevent.UnitValue Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				this._Length = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Pieces;
			case 1: return this.Weight;
			case 2: return this.Width;
			case 3: return this.Height;
			case 4: return this.Length;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Pieces = (System.Nullable<int>)fieldValue; break;
			case 1: this.Weight = (com.ineat.colistracker.historyevent.UnitValue)fieldValue; break;
			case 2: this.Width = (com.ineat.colistracker.historyevent.UnitValue)fieldValue; break;
			case 3: this.Height = (com.ineat.colistracker.historyevent.UnitValue)fieldValue; break;
			case 4: this.Length = (com.ineat.colistracker.historyevent.UnitValue)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
