// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.ineat.colistracker.historyevent
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Event : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Event"",""namespace"":""com.ineat.colistracker.historyevent"",""fields"":[{""name"":""Status"",""doc"":""Statut, ex : pre-transit"",""type"":""string""},{""name"":""Description"",""doc"":""Description, ex : The instruction data for this shipment have been provided by the sender to DHL electronically"",""type"":""string""},{""name"":""Timestamp"",""doc"":""Date du statut"",""type"":""long"",""logicalType"":""timestamp-millis""}]}");
		/// <summary>
		/// Statut, ex : pre-transit
		/// </summary>
		private string _Status;
		/// <summary>
		/// Description, ex : The instruction data for this shipment have been provided by the sender to DHL electronically
		/// </summary>
		private string _Description;
		/// <summary>
		/// Date du statut
		/// </summary>
		private long _Timestamp;
		public virtual Schema Schema
		{
			get
			{
				return Event._SCHEMA;
			}
		}
		/// <summary>
		/// Statut, ex : pre-transit
		/// </summary>
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				this._Status = value;
			}
		}
		/// <summary>
		/// Description, ex : The instruction data for this shipment have been provided by the sender to DHL electronically
		/// </summary>
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				this._Description = value;
			}
		}
		/// <summary>
		/// Date du statut
		/// </summary>
		public long Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				this._Timestamp = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Status;
			case 1: return this.Description;
			case 2: return this.Timestamp;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Status = (System.String)fieldValue; break;
			case 1: this.Description = (System.String)fieldValue; break;
			case 2: this.Timestamp = (System.Int64)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
