// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.ineat.colistracker.historyevent
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Parcel : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Parcel"",""namespace"":""com.ineat.colistracker.historyevent"",""fields"":[{""name"":""TrackingNumber"",""doc"":""Numero de suivi, ex : 00340434292135100124"",""type"":""string""},{""name"":""Carrier"",""doc"":""Transporteur, ex : DHL"",""type"":{""type"":""enum"",""name"":""Carrier"",""namespace"":""com.ineat.colistracker.historyevent"",""symbols"":[""DHL"",""LA_POSTE"",""UPS""]}}]}");
		/// <summary>
		/// Numero de suivi, ex : 00340434292135100124
		/// </summary>
		private string _TrackingNumber;
		/// <summary>
		/// Transporteur, ex : DHL
		/// </summary>
		private com.ineat.colistracker.historyevent.Carrier _Carrier;
		public virtual Schema Schema
		{
			get
			{
				return Parcel._SCHEMA;
			}
		}
		/// <summary>
		/// Numero de suivi, ex : 00340434292135100124
		/// </summary>
		public string TrackingNumber
		{
			get
			{
				return this._TrackingNumber;
			}
			set
			{
				this._TrackingNumber = value;
			}
		}
		/// <summary>
		/// Transporteur, ex : DHL
		/// </summary>
		public com.ineat.colistracker.historyevent.Carrier Carrier
		{
			get
			{
				return this._Carrier;
			}
			set
			{
				this._Carrier = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.TrackingNumber;
			case 1: return this.Carrier;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.TrackingNumber = (System.String)fieldValue; break;
			case 1: this.Carrier = (com.ineat.colistracker.historyevent.Carrier)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
