// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.ineat.colistracker.historyevent
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Wrapper : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Wrapper\",\"namespace\":\"com.ineat.colistracker.historyeven" +
				"t\",\"fields\":[{\"name\":\"Parcel\",\"doc\":\"Identification du colis\",\"type\":{\"type\":\"re" +
				"cord\",\"name\":\"Parcel\",\"namespace\":\"com.ineat.colistracker.historyevent\",\"fields\"" +
				":[{\"name\":\"TrackingNumber\",\"doc\":\"Numero de suivi, ex : 00340434292135100124\",\"t" +
				"ype\":\"string\"},{\"name\":\"Carrier\",\"doc\":\"Transporteur, ex : DHL\",\"type\":{\"type\":\"" +
				"enum\",\"name\":\"Carrier\",\"namespace\":\"com.ineat.colistracker.historyevent\",\"symbol" +
				"s\":[\"DHL\",\"LA_POSTE\",\"UPS\"]}}]}},{\"name\":\"Origin\",\"doc\":\"Adresse d\'origine\",\"typ" +
				"e\":{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"com.ineat.colistracker.history" +
				"event\",\"fields\":[{\"name\":\"CountryCode\",\"doc\":\"Code de pays, ex : DE\",\"type\":[\"nu" +
				"ll\",\"string\"]},{\"name\":\"City\",\"doc\":\"Ville, ex : Munich\",\"type\":[\"null\",\"string\"" +
				"]},{\"name\":\"ZipCode\",\"doc\":\"Code postal, ex : 59115\",\"type\":[\"null\",\"string\"]},{" +
				"\"name\":\"Localisation\",\"doc\":\"Rue / numéro / étage, ex : 30 rue du poivre\",\"type\"" +
				":[\"null\",\"string\"]}]}},{\"name\":\"Destination\",\"doc\":\"Adresse de destination\",\"typ" +
				"e\":\"Address\"},{\"name\":\"Details\",\"doc\":\"Précision sur le ou les colis\",\"type\":{\"t" +
				"ype\":\"record\",\"name\":\"Details\",\"namespace\":\"com.ineat.colistracker.historyevent\"" +
				",\"fields\":[{\"name\":\"Pieces\",\"doc\":\"Nombre de colis\",\"type\":[\"null\",\"int\"]},{\"nam" +
				"e\":\"Weight\",\"doc\":\"Poids, ex : 1.5kg\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Un" +
				"itValue\",\"namespace\":\"com.ineat.colistracker.historyevent\",\"fields\":[{\"name\":\"Va" +
				"lue\",\"doc\":\"Valeur, ex : 1.5\",\"type\":\"float\"},{\"name\":\"Unit\",\"doc\":\"Unité, ex : " +
				"kg\",\"type\":\"string\"}]}]},{\"name\":\"Width\",\"doc\":\"Largeur, ex : 50cm\",\"type\":[\"nul" +
				"l\",\"UnitValue\"]},{\"name\":\"Height\",\"doc\":\"Hauteur, ex : 1.5m\",\"type\":[\"null\",\"Uni" +
				"tValue\"]},{\"name\":\"Length\",\"doc\":\"Profondeur, ex : 300mm\",\"type\":[\"null\",\"UnitVa" +
				"lue\"]}]}},{\"name\":\"Events\",\"doc\":\"Evenements relatifs à la livraison\",\"type\":{\"t" +
				"ype\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Event\",\"namespace\":\"com.ineat.coli" +
				"stracker.historyevent\",\"fields\":[{\"name\":\"Status\",\"doc\":\"Statut, ex : pre-transi" +
				"t\",\"type\":\"string\"},{\"name\":\"Description\",\"doc\":\"Description, ex : The instructi" +
				"on data for this shipment have been provided by the sender to DHL electronically" +
				"\",\"type\":\"string\"},{\"name\":\"Timestamp\",\"doc\":\"Date du statut\",\"type\":\"long\",\"log" +
				"icalType\":\"timestamp-millis\"}]}}}]}");
		/// <summary>
		/// Identification du colis
		/// </summary>
		private com.ineat.colistracker.historyevent.Parcel _Parcel;
		/// <summary>
		/// Adresse d'origine
		/// </summary>
		private com.ineat.colistracker.historyevent.Address _Origin;
		/// <summary>
		/// Adresse de destination
		/// </summary>
		private com.ineat.colistracker.historyevent.Address _Destination;
		/// <summary>
		/// Précision sur le ou les colis
		/// </summary>
		private com.ineat.colistracker.historyevent.Details _Details;
		/// <summary>
		/// Evenements relatifs à la livraison
		/// </summary>
		private IList<com.ineat.colistracker.historyevent.Event> _Events;
		public virtual Schema Schema
		{
			get
			{
				return Wrapper._SCHEMA;
			}
		}
		/// <summary>
		/// Identification du colis
		/// </summary>
		public com.ineat.colistracker.historyevent.Parcel Parcel
		{
			get
			{
				return this._Parcel;
			}
			set
			{
				this._Parcel = value;
			}
		}
		/// <summary>
		/// Adresse d'origine
		/// </summary>
		public com.ineat.colistracker.historyevent.Address Origin
		{
			get
			{
				return this._Origin;
			}
			set
			{
				this._Origin = value;
			}
		}
		/// <summary>
		/// Adresse de destination
		/// </summary>
		public com.ineat.colistracker.historyevent.Address Destination
		{
			get
			{
				return this._Destination;
			}
			set
			{
				this._Destination = value;
			}
		}
		/// <summary>
		/// Précision sur le ou les colis
		/// </summary>
		public com.ineat.colistracker.historyevent.Details Details
		{
			get
			{
				return this._Details;
			}
			set
			{
				this._Details = value;
			}
		}
		/// <summary>
		/// Evenements relatifs à la livraison
		/// </summary>
		public IList<com.ineat.colistracker.historyevent.Event> Events
		{
			get
			{
				return this._Events;
			}
			set
			{
				this._Events = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Parcel;
			case 1: return this.Origin;
			case 2: return this.Destination;
			case 3: return this.Details;
			case 4: return this.Events;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Parcel = (com.ineat.colistracker.historyevent.Parcel)fieldValue; break;
			case 1: this.Origin = (com.ineat.colistracker.historyevent.Address)fieldValue; break;
			case 2: this.Destination = (com.ineat.colistracker.historyevent.Address)fieldValue; break;
			case 3: this.Details = (com.ineat.colistracker.historyevent.Details)fieldValue; break;
			case 4: this.Events = (IList<com.ineat.colistracker.historyevent.Event>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
