version: '3.4'

services:
  tracker:
    image: tracker:${TAG:-latest}
    depends_on:
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Tracker/Dockerfile
    ports:
      - "49111:80"

  kafka:
    image: lensesio/fast-data-dev:latest
    ports:
      - "9092:9092"
      - "8081:8081"
      - "9082:8082"
      - "9083:8083"
      - "2181:2181"
      - "3030:3030"
      - "9581-9585:9581-9585"